MERGE `crblx-beacon-prod.planning_app.price_exploration_daily` T
USING (
  SELECT
    date,
    channel_group_name,
    state,
    price_adjustment_percent,
    opps,
    bids,
    total_impressions,
    avg_position,
    sold,
    win_rate,
    avg_bid,
    cpc,
    total_spend,
    click_to_quote,
    quote_start_rate,
    number_of_quote_started,
    number_of_quotes,
    stat_sig,
    stat_sig_channel_group,
    cpc_uplift,
    cpc_uplift_channelgroup,
    win_rate_uplift,
    win_rate_uplift_channelgroup,
    additional_clicks,
    CURRENT_TIMESTAMP() AS refreshed_at
  FROM `crblx-beacon-prod.planning_app.v_price_exploration_daily`
  WHERE date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY) AND CURRENT_DATE()
) S
ON  T.date = S.date
AND T.channel_group_name = S.channel_group_name
AND T.state = S.state
AND T.price_adjustment_percent = S.price_adjustment_percent
WHEN MATCHED THEN UPDATE SET
  opps = S.opps,
  bids = S.bids,
  total_impressions = S.total_impressions,
  avg_position = S.avg_position,
  sold = S.sold,
  win_rate = S.win_rate,
  avg_bid = S.avg_bid,
  cpc = S.cpc,
  total_spend = S.total_spend,
  click_to_quote = S.click_to_quote,
  quote_start_rate = S.quote_start_rate,
  number_of_quote_started = S.number_of_quote_started,
  number_of_quotes = S.number_of_quotes,
  stat_sig = S.stat_sig,
  stat_sig_channel_group = S.stat_sig_channel_group,
  cpc_uplift = S.cpc_uplift,
  cpc_uplift_channelgroup = S.cpc_uplift_channelgroup,
  win_rate_uplift = S.win_rate_uplift,
  win_rate_uplift_channelgroup = S.win_rate_uplift_channelgroup,
  additional_clicks = S.additional_clicks,
  refreshed_at = S.refreshed_at
WHEN NOT MATCHED THEN INSERT (
  date,
  channel_group_name,
  state,
  price_adjustment_percent,
  opps,
  bids,
  total_impressions,
  avg_position,
  sold,
  win_rate,
  avg_bid,
  cpc,
  total_spend,
  click_to_quote,
  quote_start_rate,
  number_of_quote_started,
  number_of_quotes,
  stat_sig,
  stat_sig_channel_group,
  cpc_uplift,
  cpc_uplift_channelgroup,
  win_rate_uplift,
  win_rate_uplift_channelgroup,
  additional_clicks,
  refreshed_at
)
VALUES (
  S.date,
  S.channel_group_name,
  S.state,
  S.price_adjustment_percent,
  S.opps,
  S.bids,
  S.total_impressions,
  S.avg_position,
  S.sold,
  S.win_rate,
  S.avg_bid,
  S.cpc,
  S.total_spend,
  S.click_to_quote,
  S.quote_start_rate,
  S.number_of_quote_started,
  S.number_of_quotes,
  S.stat_sig,
  S.stat_sig_channel_group,
  S.cpc_uplift,
  S.cpc_uplift_channelgroup,
  S.win_rate_uplift,
  S.win_rate_uplift_channelgroup,
  S.additional_clicks,
  S.refreshed_at
);
